package com.a40610.appannotation.background.utils

object Constants {
    const val type = "type"
    const val annotation = "annotation"
    const val sensorContact = "sensorContact"
    const val heartRateValue = "heartRateValue"
    const val energyExpended = "energyExpended"
    const val rrInterval = "rrInterval"
    const val timestamp = "timestamp"
    const val empty = ""
    const val heartRateMeasurement = "Heart Rate Measurement"
    const val hrm = "hrm"
    const val batteryLevel = "Battery Level"
    const val br = "br"
    const val activity = "activity"
    const val hrp = "hrp"
    const val ppg = "ppg"
    const val data = "data"
    const val notify = "notify"
    const val read = "read"
    const val write = "write"
    const val pulseOnName = "hBAND"
    const val maximName = "HSP2SPO2"
    const val rollingCounter = "rollingCounter"
    const val hRReliable = "hRReliable"
    const val hRatTimeout = "hRatTimeout"
    const val newIBIData = "newIBIData"
    const val hRQuality = "hRQuality"
    const val ibi = "ibi"
    const val ibiQuality = "ibiQuality"
    const val level = "level"
    const val hr = "hr"
    const val sleep_data_present = "sleep_data_present"
    const val speed_data_present = "speed_data_present"
    const val distance_data_present = "distance_data_present"
    const val swim_data_present = "swim_data_present"
    const val workout_status_changed = "workout_status_changed"
    const val worn_status_changed = "worn_status_changed"
    const val activity_data_changed = "activity_data_changed"
    const val k_calories = "k_calories"
    const val speed = "speed"
    const val steps = "steps"
    const val distance = "distance"
    const val activity_type = "activity_type"
    const val workout_state = "workout_state"
    const val worn_state = "worn_state"
    const val time = "time"

}